// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prediction_service.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tensorflow.Serving {

  /// <summary>Holder for reflection information generated from prediction_service.proto</summary>
  public static partial class PredictionServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for prediction_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PredictionServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhwcmVkaWN0aW9uX3NlcnZpY2UucHJvdG8SEnRlbnNvcmZsb3cuc2Vydmlu",
            "ZxosdGVuc29yZmxvd19zZXJ2aW5nL2FwaXMvY2xhc3NpZmljYXRpb24ucHJv",
            "dG8aMHRlbnNvcmZsb3dfc2VydmluZy9hcGlzL2dldF9tb2RlbF9tZXRhZGF0",
            "YS5wcm90bxondGVuc29yZmxvd19zZXJ2aW5nL2FwaXMvaW5mZXJlbmNlLnBy",
            "b3RvGiV0ZW5zb3JmbG93X3NlcnZpbmcvYXBpcy9wcmVkaWN0LnByb3RvGih0",
            "ZW5zb3JmbG93X3NlcnZpbmcvYXBpcy9yZWdyZXNzaW9uLnByb3RvMvwDChFQ",
            "cmVkaWN0aW9uU2VydmljZRJhCghDbGFzc2lmeRIpLnRlbnNvcmZsb3cuc2Vy",
            "dmluZy5DbGFzc2lmaWNhdGlvblJlcXVlc3QaKi50ZW5zb3JmbG93LnNlcnZp",
            "bmcuQ2xhc3NpZmljYXRpb25SZXNwb25zZRJYCgdSZWdyZXNzEiUudGVuc29y",
            "Zmxvdy5zZXJ2aW5nLlJlZ3Jlc3Npb25SZXF1ZXN0GiYudGVuc29yZmxvdy5z",
            "ZXJ2aW5nLlJlZ3Jlc3Npb25SZXNwb25zZRJSCgdQcmVkaWN0EiIudGVuc29y",
            "Zmxvdy5zZXJ2aW5nLlByZWRpY3RSZXF1ZXN0GiMudGVuc29yZmxvdy5zZXJ2",
            "aW5nLlByZWRpY3RSZXNwb25zZRJnCg5NdWx0aUluZmVyZW5jZRIpLnRlbnNv",
            "cmZsb3cuc2VydmluZy5NdWx0aUluZmVyZW5jZVJlcXVlc3QaKi50ZW5zb3Jm",
            "bG93LnNlcnZpbmcuTXVsdGlJbmZlcmVuY2VSZXNwb25zZRJtChBHZXRNb2Rl",
            "bE1ldGFkYXRhEisudGVuc29yZmxvdy5zZXJ2aW5nLkdldE1vZGVsTWV0YWRh",
            "dGFSZXF1ZXN0GiwudGVuc29yZmxvdy5zZXJ2aW5nLkdldE1vZGVsTWV0YWRh",
            "dGFSZXNwb25zZUID+AEBYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Tensorflow.Serving.ClassificationReflection.Descriptor, global::Tensorflow.Serving.GetModelMetadataReflection.Descriptor, global::Tensorflow.Serving.InferenceReflection.Descriptor, global::Tensorflow.Serving.PredictReflection.Descriptor, global::Tensorflow.Serving.RegressionReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
